project:
  type: website
  output-dir: docs

website:
  title: "Xpo"
  navbar:
    left:
      - href: ans.ipynb
        text: Notebook
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



